name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Renamer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/McRename.sln
    - name: Build
      run: dotnet build src/McRename.sln --configuration Release --no-restore

    - name: Test Renamer
      if: success()
      run: dotnet test src/RenamerTests/RenamerTests.csproj --no-restore --verbosity normal

    - name: Publish Renamer NuGet Package
      if: success()
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/Renamer/Renamer.csproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: Renamer
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{secrets.NUGET}}

  Terminal:
    needs: Renamer
    runs-on: ubuntu-latest
    
    steps:
      - run: dotnet test src/TerminalTests/TerminalTests.csproj --no-restore --verbosity normal
